[project]
name = "bidi_agent"
version = "0.1.0"
description = "Example of deploying a Bidi Agent on Cloud Run"
requires-python = ">=3.10"
dependencies = [
    "google-adk==1.4.2",
    "python-dotenv==1.1.1",
    "starlette==0.46.2",
    "uvicorn==0.34.3",
]
