// AUTO-GENERATED by scripts/gen-tenant-config.mjs from tenants/*.json.
// Do NOT edit by hand — edit the manifests and re-run the generator.

export const MODULE_CATALOG = {
  "core": {
    "agents": [
      "session_naming_agent"
    ],
    "services": [
      "gateway",
      "agents",
      "mcp-stats",
      "frontend"
    ]
  },
  "modules": {
    "plan": {
      "label": "Plan",
      "route": "/plan",
      "description": "Build and edit media plans by client. Campaigns, lines, creatives — joined to live performance.",
      "agents": [
        "data_agent"
      ],
      "services": [
        "mcp-toolbox"
      ],
      "capabilities": []
    },
    "dashboards": {
      "label": "Dashboards",
      "route": "/dashboards",
      "description": "Access your reports and shared dashboards. Monitor performance across campaigns, clients, and channels.",
      "agents": [
        "dashboard_insights_agent",
        "dashboard_editor_agent"
      ],
      "services": [
        "mcp-toolbox"
      ],
      "capabilities": [
        "floatingAssistant",
        "pinToDashboard"
      ]
    },
    "autocorr": {
      "label": "AutoCorr",
      "route": "/autocorr",
      "description": "Auto-correlate drivers against KPIs across any data source. Upload data, run the analysis, save the visuals.",
      "agents": [
        "autocorr_assistant_agent"
      ],
      "services": [],
      "capabilities": []
    },
    "market-radar": {
      "label": "Market Radar",
      "route": "/market-radar",
      "description": "Estimate competitor media spend, share-of-voice, and model support from MediaRadar / Pathmatics exports.",
      "agents": [
        "market_radar_assistant_agent",
        "market_radar_insights_agent"
      ],
      "services": [],
      "capabilities": []
    },
    "agents": {
      "label": "Agents",
      "route": "/agents",
      "description": "AI-powered agents for media analysis, timesheets, and more. Pick one to start a conversation.",
      "agents": [
        "media_performance_agent",
        "timesheet_agent",
        "dashboard_editor_agent"
      ],
      "services": [
        "mcp-toolbox"
      ],
      "capabilities": [
        "floatingAssistant"
      ]
    }
  }
} as const;

export const TENANTS = {
  "csa": {
    "id": "csa",
    "projectPrefix": "nd-csa",
    "enabledModules": [
      "autocorr",
      "market-radar"
    ],
    "analytics": {
      "measurementId": ""
    },
    "branding": {
      "brandName": "CSAos",
      "logo": "/csa/csa_white.png",
      "logoAlt": "CSAos",
      "logoInvertOnLight": true,
      "emailDomain": "globalservs.com",
      "favicon": "/csa/csa_favicon.png",
      "tagline": "Competitive media intelligence — estimate spend, share of voice, and correlate what moves your KPIs.",
      "accent": {
        "100": "#fde3e4",
        "300": "#f59a9e",
        "400": "#ee5158",
        "500": "#e50914",
        "600": "#c20510",
        "900": "#6b070f",
        "950": "#45060a",
        "onDark": "#f4636b",
        "onLight": "#c20510"
      },
      "defaultTheme": "dark",
      "font": {
        "sans": "var(--font-geist-sans), ui-sans-serif, system-ui, sans-serif",
        "display": "var(--font-geist-sans), ui-sans-serif, system-ui, sans-serif"
      },
      "charts": {
        "bar": "#e50914",
        "line": "#f4636b",
        "categorical": [
          "#e50914",
          "#f4636b",
          "#c20510",
          "#ff8a93",
          "#f59e0b",
          "#06b6d4",
          "#84cc16",
          "#8b5cf6"
        ],
        "heatmap": [
          "#3c050e",
          "#6b070f",
          "#c20510",
          "#f4636b"
        ],
        "ramp": [
          "#45060a",
          "#6b070f",
          "#e50914",
          "#f4636b"
        ]
      },
      "palette": {
        "--c-orb-a": "rgba(229, 9, 20, 0.5)",
        "--c-orb-b": "rgba(180, 5, 16, 0.42)",
        "--c-orb-c": "rgba(120, 5, 12, 0.4)",
        "--c-orb-d": "rgba(255, 82, 92, 0.32)"
      }
    }
  },
  "noise": {
    "id": "noise",
    "projectPrefix": "nd-agentspace",
    "enabledModules": [
      "plan",
      "dashboards",
      "agents"
    ],
    "analytics": {
      "measurementId": "G-PSTSB8D377"
    },
    "branding": {
      "brandName": "NoiseOS",
      "logo": "/noise/noise_white.svg",
      "logoAlt": "Noise",
      "logoInvertOnLight": true,
      "emailDomain": "noisedigital.com",
      "favicon": "/noise/noise_favicon.ico",
      "tagline": "Your platform for media planning, reporting, and AI-powered tools. Pick a section below to get started.",
      "accent": {
        "100": "#dbeafe",
        "300": "#93c5fd",
        "400": "#60a5fa",
        "500": "#3b82f6",
        "600": "#2563eb",
        "900": "#1e3a8a",
        "950": "#172554",
        "onDark": "#60a5fa",
        "onLight": "#2563eb"
      },
      "defaultTheme": "system",
      "font": {
        "sans": "var(--font-geist-sans), ui-sans-serif, system-ui, sans-serif",
        "display": "var(--font-geist-sans), ui-sans-serif, system-ui, sans-serif"
      },
      "charts": {
        "bar": "#10b981",
        "line": "#3b82f6",
        "categorical": [
          "#10b981",
          "#3b82f6",
          "#f59e0b",
          "#8b5cf6",
          "#ec4899",
          "#06b6d4",
          "#84cc16",
          "#f97316"
        ],
        "heatmap": [
          "#0b3b2e",
          "#0f766e",
          "#10b981",
          "#6ee7b7"
        ],
        "ramp": [
          "#172554",
          "#1e40af",
          "#3b82f6",
          "#93c5fd"
        ]
      },
      "palette": {
        "--c-orb-a": "rgba(16, 185, 129, 0.55)",
        "--c-orb-b": "rgba(59, 130, 246, 0.55)",
        "--c-orb-c": "rgba(139, 92, 246, 0.50)",
        "--c-orb-d": "rgba(236, 72, 153, 0.42)"
      }
    }
  }
} as const;
