// Type-checks EVERY tenant's content against the TenantContent contract — not
// just the build-time active one. Nothing imports this, so it never ships in a
// bundle; it exists so `tsc` validates all tenants. Generated by
// scripts/new-tenant.sh — do not edit by hand.
import type { TenantContent } from "./types";
import * as csa from "./csa";
import * as noise from "./noise";

export const _allTenantContent: TenantContent[] = [csa, noise];
