#!/usr/bin/env bash
# Scaffold a new tenant end-to-end: manifest → frontend config → infra stage →
# local-dev task. The four things every tenant needs (modules, config, run, deploy)
# start here; what this can't do for you (cloud project, bootstrap, GitHub env) is
# printed as next steps.
#
# Usage:  scripts/new-tenant.sh <tenant-id> <project-prefix> [module ...]
#   e.g.  scripts/new-tenant.sh acme nd-acme analyze dashboards
# Modules default to "analyze". Branding is seeded with placeholders — edit
# tenants/<id>.json, then re-run `node scripts/gen-tenant-config.mjs`.
set -euo pipefail

ID="${1:-}"
PREFIX="${2:-}"
if [ -z "$ID" ] || [ -z "$PREFIX" ]; then
  echo "usage: scripts/new-tenant.sh <tenant-id> <project-prefix> [module ...]"
  exit 1
fi
shift 2
MODULES=("$@")
[ ${#MODULES[@]} -eq 0 ] && MODULES=(analyze)

echo "$ID" | grep -qE '^[a-z][a-z0-9-]*$' || { echo "✘ tenant id must be lowercase kebab-case"; exit 1; }

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

[ -e "tenants/$ID.json" ] && { echo "✘ tenants/$ID.json already exists"; exit 1; }
[ -e "infra/tenants/$ID" ] && { echo "✘ infra/tenants/$ID already exists"; exit 1; }

BRAND="$(echo "$ID" | tr '[:lower:]' '[:upper:]')"
MODS_JSON="[$(printf '"%s",' "${MODULES[@]}" | sed 's/,$//')]"

echo "→ tenant '$ID' (project prefix '$PREFIX'), modules: ${MODULES[*]}"

# ── 1. Tenant manifest (branding seeded from a neutral ramp — REPLACE it) ─────
cat > "tenants/$ID.json" <<EOF
{
  "_comment": "Tenant $ID. enabledModules drives frontend nav, agents (ENABLED_AGENTS), and infra services everywhere.",
  "_placeholder": "Replace branding.accent with the real brand ramp and drop ${ID}_white.svg into services/frontend/public/, then run: node scripts/gen-tenant-config.mjs",
  "id": "$ID",
  "projectPrefix": "$PREFIX",
  "enabledModules": $MODS_JSON,
  "_analytics": "This tenant's OWN GA4 destination — no shared default, so it can never hit another tenant's property. Empty = analytics off. Set to this tenant's GA4 web-stream id (G-XXXX) once the property exists.",
  "analytics": {
    "measurementId": ""
  },
  "branding": {
    "brandName": "$BRAND",
    "logo": "/${ID}/${ID}_white.svg",
    "logoAlt": "$BRAND",
    "logoInvertOnLight": false,
    "emailDomain": "example.com",
    "favicon": "/${ID}/${ID}-favicon.ico",
    "accent": {
      "100": "#dbeafe", "300": "#93c5fd", "400": "#60a5fa", "500": "#3b82f6",
      "600": "#2563eb", "900": "#1e3a8a", "950": "#172554",
      "onDark": "#60a5fa", "onLight": "#2563eb"
    },
    "defaultTheme": "system",
    "font": {
      "sans": "var(--font-geist-sans), ui-sans-serif, system-ui, sans-serif",
      "display": "var(--font-geist-sans), ui-sans-serif, system-ui, sans-serif"
    },
    "charts": {
      "bar": "#10b981",
      "line": "#3b82f6",
      "categorical": ["#10b981", "#3b82f6", "#f59e0b", "#8b5cf6", "#ec4899", "#06b6d4", "#84cc16", "#f97316"],
      "heatmap": ["#0b3b2e", "#0f766e", "#10b981", "#6ee7b7"],
      "ramp": ["#172554", "#1e40af", "#3b82f6", "#93c5fd"]
    }
  }
}
EOF
echo "  ✓ tenants/$ID.json"

# ── 2. Frontend config (regenerate the committed slice) ──────────────────────
node scripts/gen-tenant-config.mjs >/dev/null
echo "  ✓ regenerated services/frontend/src/config/tenants.gen.ts"

# ── 2b. Frontend content dir (empty) — the @tenant-content alias resolves to
# src/data/tenants/<id>/, so every tenant needs one even with no plan/dashboard
# content. Fill it in if this tenant enables content modules (see data/tenants/noise).
CONTENT_DIR="services/frontend/src/data/tenants/$ID"
mkdir -p "$CONTENT_DIR"
cat > "$CONTENT_DIR/clients.ts" <<EOF
// $ID tenant — client registry seed. Empty until this tenant has clients.
import type { Client } from "@/data/media-model";

export const clients: Client[] = [];
export const KNOWN_CLIENT_CODES = [] as const;
EOF
cat > "$CONTENT_DIR/index.ts" <<EOF
// $ID tenant content. Same export surface as every tenant index (../types.ts).
import type { Dashboard } from "@/data/dashboards/types";
import type { ClientPlan } from "@/data/plans/types";

export { clients, KNOWN_CLIENT_CODES } from "./clients";
export const clientDashboards: Dashboard[] = [];
export const clientPlans: ClientPlan[] = [];
EOF
# Regenerate the typecheck-all index from the content dirs present.
node - <<'NODE'
const fs = require("fs"), path = require("path");
const dir = "services/frontend/src/data/tenants";
const ids = fs.readdirSync(dir, { withFileTypes: true })
  .filter((d) => d.isDirectory()).map((d) => d.name).sort();
const bind = (i) => i.replace(/[^a-zA-Z0-9_$]/g, "_");
const imports = ids.map((i) => `import * as ${bind(i)} from "./${i}";`).join("\n");
const items = ids.map((i) => bind(i)).join(", ");
fs.writeFileSync(path.join(dir, "_all.ts"),
`// Type-checks EVERY tenant's content against the TenantContent contract — not
// just the build-time active one. Nothing imports this, so it never ships in a
// bundle; it exists so \`tsc\` validates all tenants. Generated by
// scripts/new-tenant.sh — do not edit by hand.
import type { TenantContent } from "./types";
${imports}

export const _allTenantContent: TenantContent[] = [${items}];
`);
NODE
echo "  ✓ $CONTENT_DIR/ (empty content) + regenerated _all.ts"

# ── 3. Infra stage (copy noise's tenant-agnostic files, template main.tf) ────
mkdir -p "infra/tenants/$ID/env" "infra/tenants/$ID/backend"
cp infra/tenants/noise/variables.tf infra/tenants/noise/versions.tf "infra/tenants/$ID/"

cat > "infra/tenants/$ID/main.tf" <<'EOF'
# ── Tenant: __ID__ ────────────────────────────────────────────────────────────
# ONE config for ALL of this tenant's stages (make apply TENANT=__ID__ STAGE=sbx).
# Which modules/services/agents this tenant gets is derived from tenants/__ID__.json
# by the tenant module (infra/modules/tenant/modules.tf) — not set here.

locals {
  tenant_id      = "__ID__"
  project_prefix = "__PREFIX__"
  project_id     = var.project_id != "" ? var.project_id : "${local.project_prefix}-${var.stage}"
}

provider "google" {
  project               = local.project_id
  region                = var.region
  user_project_override = true
  billing_project       = local.project_id
}

provider "google-beta" {
  project               = local.project_id
  region                = var.region
  user_project_override = true
  billing_project       = local.project_id
}

module "tenant" {
  source = "../../modules/tenant"

  tenant_id  = local.tenant_id
  stage      = var.stage
  project_id = local.project_id
  region     = var.region

  vertex_location = "global"
  db_tier         = var.db_tier

  admin_emails               = var.admin_emails
  google_oauth_client_id     = var.google_oauth_client_id
  google_oauth_client_secret = var.google_oauth_client_secret

  enable_sgtm              = var.enable_sgtm
  enable_datastream        = var.enable_datastream
  datastream_create_stream = var.datastream_create_stream
}

output "project_id" { value = module.tenant.project_id }
output "frontend_url" { value = module.tenant.frontend_url }
output "gateway_url" { value = module.tenant.gateway_url }
output "migrate_job" { value = module.tenant.migrate_job }
output "firebase_web_config" {
  value     = module.tenant.firebase_web_config
  sensitive = true
}
output "sgtm_url" { value = module.tenant.sgtm_url }
output "datastream_bq_dataset" { value = module.tenant.datastream_bq_dataset }
EOF
sed -i "s/__ID__/$ID/g; s/__PREFIX__/$PREFIX/g" "infra/tenants/$ID/main.tf"

cat > "infra/tenants/$ID/env/sbx.tfvars" <<EOF
# $ID / sbx → project $PREFIX-sbx (derived <project_prefix>-<stage>).
stage = "sbx"

# TODO($ID): set the real admin email(s) before first apply.
admin_emails = ["TODO@example.com"]

db_tier = "db-f1-micro"

# Orthogonal infra features off by default (modules/services are derived from
# tenants/$ID.json, not toggled here).
enable_sgtm              = false
enable_datastream        = false
datastream_create_stream = false
EOF

cat > "infra/tenants/$ID/backend/sbx.hcl" <<EOF
bucket = "$PREFIX-sbx-tfstate"
prefix = "tenants/$ID/sbx"
EOF
echo "  ✓ infra/tenants/$ID/ (main.tf, variables.tf, versions.tf, env/sbx.tfvars, backend/sbx.hcl)"

# ── 4. VS Code Start task ────────────────────────────────────────────────────
node - "$ID" <<'EOF'
const fs = require("fs");
const id = process.argv[2];
const p = ".vscode/tasks.json";
const cfg = JSON.parse(fs.readFileSync(p, "utf8"));
const label = `Start Services: ${id}`;
if (!cfg.tasks.some((t) => t.label === label)) {
  cfg.tasks.push({
    label,
    type: "shell",
    command: `TENANT=${id} bash scripts/start_services.sh`,
    options: { cwd: "${workspaceFolder}" },
    presentation: { reveal: "always", panel: "dedicated", focus: true, showReuseMessage: false, clear: true },
    problemMatcher: [],
  });
  fs.writeFileSync(p, JSON.stringify(cfg, null, 4) + "\n");
  console.log(`  ✓ added VS Code task "${label}"`);
} else {
  console.log(`  • VS Code task "${label}" already present`);
}
EOF

# ── 4b. Firebase project alias (firebase CLI / emulator targeting per tenant) ──
node - "$ID" "$PREFIX" <<'EOF'
const fs = require("fs");
const [id, prefix] = process.argv.slice(2);
const p = ".firebaserc";
const rc = JSON.parse(fs.readFileSync(p, "utf8"));
rc.projects ||= {};
rc.projects[`${id}-sbx`] = `${prefix}-sbx`;
fs.writeFileSync(p, JSON.stringify(rc, null, 2) + "\n");
console.log(`  ✓ .firebaserc alias ${id}-sbx → ${prefix}-sbx`);
EOF

# ── 5. Validate + next steps ─────────────────────────────────────────────────
node scripts/lint-tenants.mjs || true
cat <<EOF

✔ Tenant '$ID' scaffolded. Next:
  1. Branding   — edit tenants/$ID.json (accent ramp), add services/frontend/public/${ID}_white.svg,
                  then: node scripts/gen-tenant-config.mjs
  2. Modules    — adjust "enabledModules" in tenants/$ID.json if needed
  3. Admin      — set admin_emails in infra/tenants/$ID/env/sbx.tfvars
  4. Run local  — TENANT=$ID ./scripts/start_services.sh  (or the new VS Code task)
  5. Deploy     — create GCP project ${PREFIX}-sbx (+ billing); add it to
                  infra/bootstrap/terraform.tfvars target_projects and re-apply;
                  create a GitHub Environment '${ID}-sbx' (DEPLOY_PROJECT, NEXT_PUBLIC_TENANT=$ID,
                  shared AR/WIF/SA, Firebase app id); then: make apply TENANT=$ID STAGE=sbx
EOF
